enabled: true
 # Lore of the USword
 # Variables :
 # xp - XP of the sword
 # playerName - name of the player who got the Sword
 # Tell me if you want more
swordLore:
  - '{playerName}''s Upgradeable Sword'
  - 'Exp : {xp}'
 # The Display Name of the Upgradeable Sword
swordname: '&l&4Monster of Death'
 # Rate of getting XP
 # 2 xprate means 2 xp per 1 hit
 # -2 xprate means 1 xp per 2 hit
xprate: 1
 # Levels of Enchantment
 # Each index of these Integers represents the xp for a level of The Enchantment
 # eg. 100 xp is needed for sharpness level 1 in this default config and so on
 #     5000 xp is needed for fire aspect level 2
levels:
   # Levels for Fire Aspect enchantment
  fireaspect:
    - 0
    - 2000
    - 5000
   # Levels for Sharpness enchantment
  sharpness:
    - 0
    - 100
    - 500
    - 1000
    - 3000
    - 8000
   # Levels for Life-Steal enchantment
  lifesteal:
    - 0
    - 4000
    - 7000
    - 10000

 # Message after Level up (Enchantment Added)
 # Variables :
 # enchantment - The Enchantment added
 # level - The Enchantment Level
 # Tell me if you want more
levelUpMessage: 'Your sword leveled up!! {enchantment} {level} Added.'
 # Message sent after Using the usword command
 # Gimme a better name ;-;
swordGaveMessage: 'Check your inventory for the Upgradeable Sword!!!'
 # The number of hits after which it should Alert staff
 # Better name...
maxHitsAlert: 30
