name: UpgradeableSword
main: gg.solarmc.upgradeablesword.UpgradeableSword
version: ${project.version}
authors: [ zone_infinity ]
commands:
  usword:
    description: "The only command of USword Plugin"
    usage: /<command>